Token: 5063239240:AAGF773wb_DvxPb9LlNUIkMb-7HNA6Aw834
PriceOneMonth: '1.0'
PriceForever: '499.0'
QiwiPublicKey: "48e7qUxn9T7RyYE1MVZswX1FRSbE6iyCj2gCRwwF3Dnh5XrasNTx3BGPiMsyXQFNKQhvukniQG8RTVhYm3iPxZREA6XAtpGx5VrgDGq1d4D3RsHRcZJBrocXPXwPdaFDmgE1mQcXSAsAZRWe336suGRbN5EYmvsNBFgA8oqxtkPHHVAWNLNTMBkHoFJMc"
QiwiSecretKey: "eyJ2ZXJzaW9uIjoiUDJQIiwiZGF0YSI6eyJwYXlpbl9tZXJjaGFudF9zaXRlX3VpZCI6InYxZGN6ai0wMCIsInVzZXJfaWQiOiIzNzUyOTcxMDc5MTAiLCJzZWNyZXQiOiI1OTFjMTE1YzA4ZmE2MDA5ZWYyZDE4NDY2ZGM1MTdiYTg1MzI1MWJiZWZiZjRiYzZhNDg3NDNlNmNlOWE4YTg0In19"
